In [ ]:
!git clone https://github.com/Jayeshwaykar/Book-Recommendation-System.git

fatal: destination path 'Book-Recommendation-System' already exists and is not an empty directory.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
books = pd.read_csv("/content/drive/MyDrive/Book Recommendation System/Books.csv")
ratings = pd.read_csv("/content/drive/MyDrive/Book Recommendation System/Ratings.csv")
users = pd.read_csv("/content/drive/MyDrive/Book Recommendation System/Users.csv")

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [ ]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [ ]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [ ]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [ ]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [ ]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [ ]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [ ]:
books.duplicated().sum()

0

In [ ]:
users.duplicated().sum()

0

In [ ]:
ratings.duplicated().sum()

0

Popularity Based Recommender Systems

In [ ]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [ ]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [ ]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [ ]:
num_rating_df.rename(columns={'Book-Rating':'num-ratings'},inplace= True)

In [ ]:
num_rating_df

                                               Book-Title  num-ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [ ]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg-ratings'},inplace= True)
avg_rating_df

                                               Book-Title  avg-ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [ ]:
popular_df = num_rating_df.merge(avg_rating_df,on="Book-Title")
popular_df

,Book-Title,num-ratings,avg-ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [ ]:
popular_df[popular_df['num-ratings']>=250]

,Book-Title,num-ratings,avg-ratings
764,1984,284,4.454225
818,1st to Die: A Novel,509,3.575639
1048,2nd Chance,356,3.269663
1760,A Bend in the Road,346,3.364162
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
...,...,...,...
233850,White Oleander : A Novel,387,3.506460
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472
234740,Wicked: The Life and Times of the Wicked Witch...,326,3.766871
234951,Wild Animus,2502,1.019584
240860,"\O\"" Is for Outlaw""",269,2.988848

In [ ]:
popular_df = popular_df[popular_df['num-ratings']>=250].sort_values('avg-ratings',ascending = False).head(50)

In [ ]:
popular_df.merge(books,on="Book-Title").drop_duplicates('Book-Title')

,Book-Title,num-ratings,avg-ratings,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410,0590353403,J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,043935806X,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,0439064872,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117,0345339681,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...
17,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370,0345339703,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652,059035342X,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...
28,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769,0345339711,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339711.0...,http://images.amazon.com/images/P/0345339711.0...,http://images.amazon.com/images/P/0345339711.0...
39,To Kill a Mockingbird,510,4.700000,0446310786,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
47,The Da Vinci Code,898,4.642539,0385504209,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...
53,The Five People You Meet in Heaven,430,4.551163,0786868716,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...
55,The Catcher in the Rye,449,4.545657,0316769487,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...
62,The Lovely Bones: A Novel,1295,4.468726,0316666343,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...
63,1984,284,4.454225,0451524934,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...
72,Prodigal Summer: A Novel,253,4.450593,0060959037,Barbara Kingsolver,2001,Perennial,http://images.amazon.com/images/P/0060959037.0...,http://images.amazon.com/images/P/0060959037.0...,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,265,4.449057,0380789019,Neil Gaiman,1998,Avon,http://images.amazon.com/images/P/0380789019.0...,http://images.amazon.com/images/P/0380789019.0...,http://images.amazon.com/images/P/0380789019.0...
78,The Secret Life of Bees,774,4.447028,0142001740,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890,0060392452,Michael Moore,2002,Regan Books,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,0385484518,MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),723,4.334716,0312195516,Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...
89,The Hitchhiker's Guide to the Galaxy,268,4.328358,0671461494,Douglas Adams,1982,Pocket,http://images.amazon.com/images/P/0671461494.0...,http://images.amazon.com/images/P/0671461494.0...,http://images.amazon.com/images/P/0671461494.0...
98,Nickel and Dimed: On (Not) Getting By in America,335,4.289552,0805063897,Barbara Ehrenreich,2002,Owl Books,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...
100,Into the Wild,252,4.273810,0385486804,Jon Krakauer,1997,Anchor,http://images.amazon.com/images/P/0385486804.0...,http://images.amazon.com/images/P/0385486804.0...,http://images.amazon.com/images/P/0385486804.0...
103,Fahrenheit 451,409,4.264059,3257208626,Ray Bradbury,1994,Distribooks Inc,http://images.amazon.com/images/P/3257208626.0...,http://images.amazon.com/images/P/3257208626.0...,http://images.amazon.com/images/P/3257208626.0...
116,Girl with a Pearl Earring,526,4.218631,0452282152,Tracy Chevalier,2001,Plume Books,http://images.amazon.com/images/P/0452282152.0...,http://images.amazon.com/images/P/0452282152.0...,http://images.amazon.com/images/P/0452282152.0...
117,Outlander,283,4.173145,0440222915,DIANA GABALDON,1996,Dell,http://images.amazon.com/images/P/0440222915.0...,http://images.amazon.com/images/P/0440222915.0...,http://images.amazon.com/images/P/0440222915.0...
123,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983,0446672211,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...,http://images.amazon.com/images/P/0446672211.0...,http://images.amazon.com/images/P/0446672211.0...
124,Seabiscuit: An American Legend,275,4.098182,0449005615,LAURA HILLENBRAND,2002,Ballantine Books,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...
126,Life of Pi,664,4.088855,0151008116,Yann Martel,2002,Harcourt,http://images.amazon.com/images/P/0151008116.0...,http://images.amazon.com/images/P/0151008116.0...,http://images.amazon.com/images/P/0151008116.0...
130,The Bean Trees,389,4.087404,0060915544,Barbara Kingsolver,1989,Perennial,http://images.amazon.com/images/P/0060915544.0...,http://images.amazon.com/images/P/0060915544.0...,http://images.amazon.com/images/P/0060915544.0...
133,"A Child Called \It\"": One Child's Courage to S...",265,4.086792,1558743669,Dave Pelzer,1995,Health Communications,http://images.amazon.com/images/P/1558743669.0...,http://images.amazon.com/images/P/1558743669.0...,http://images.amazon.com/images/P/1558743669.0...
135,ANGELA'S ASHES,279,4.075269,0684874350,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...
137,Good in Bed,490,4.055102,0743418174,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...,http://images.amazon.com/images/P/0743418174.0...,http://images.amazon.com/images/P/0743418174.0...
139,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383,0060938455,Eric Schlosser,2002,Perennial,http://images.amazon.com/images/P/0060938455.0...,http://images.amazon.com/images/P/0060938455.0...,http://images.amazon.com/images/P/0060938455.0...
140,American Gods,302,4.006623,0380789035,Neil Gaiman,2002,HarperTorch,http://images.amazon.com/images/P/0380789035.0...,http://images.amazon.com/images/P/0380789035.0...,http://images.amazon.com/images/P/0380789035.0...
141,Skipping Christmas,322,4.006211,0385505833,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/0385505833.0...,http://images.amazon.com/images/P/0385505833.0...,http://images.amazon.com/images/P/0385505833.0...
147,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145,0842329129,Tim Lahaye,1996,Tyndale House Publishers,http://images.amazon.com/images/P/0842329129.0...,http://images.amazon.com/images/P/0842329129.0...,http://images.amazon.com/images/P/0842329129.0...
149,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000,037582345X,PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...
157,The Color Purple,314,3.964968,0671617028,Alice Walker,1985,Pocket Books,http://images.amazon.com/images/P/0671617028.0...,http://images.amazon.com/images/P/0671617028.0...,http://images.amazon.com/images/P/0671617028.0...
163,Silence of the Lambs,256,3.960938,0312924585,Thomas Harris,1991,St. Martin's Press,http://images.amazon.com/images/P/0312924585.0...,http://images.amazon.com/images/P/0312924585.0...,http://images.amazon.com/images/P/0312924585.0...
166,About a Boy,262,3.900763,1573227331,Nick Hornby,1999,Riverhead Books,http://images.amazon.com/images/P/1573227331.0...,http://images.amazon.com/images/P/1573227331.0...,http://images.amazon.com/images/P/1573227331.0...
173,Seven Up (A Stephanie Plum Novel),278,3.888489,0312265840,Janet Evanovich,2001,St. Martin's Press,http://images.amazon.com/images/P/0312265840.0...,http://images.amazon.com/images/P/0312265840.0...,http://images.amazon.com/images/P/0312265840.0...
175,The Alchemist: A Fable About Following Your Dream,266,3.875940,0062502174,Paulo Coelho,1993,HarperSanFrancisco,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279,0312983867,Janet Evanovich,2003,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312983867.0...,http://images.amazon.com/images/P/0312983867.0...,http://images.amazon.com/images/P/0312983867.0...
182,Suzanne's Diary for Nicholas,457,3.820569,0316969443,James Patterson,2001,"Little, Brown",http://images.amazon.com/images/P/0316969443.0...,http://images.amazon.com/images/P/0316969443.0...,http://images.amazon.com/images/P/0316969443.0...
186,Lord of the Flies,259,3.818533,0399501487,William Gerald Golding,1959,Perigee Trade,http://images.amazon.com/images/P/0399501487.0...,http://images.amazon.com/images/P/0399501487.0...,http://images.amazon.com/images/P/0399501487.0...
192,A Prayer for Owen Meany,413,3.796610,0345361792,John Irving,1990,Ballantine Books,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409,0345313860,ANNE RICE,1986,Ballantine Books,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),356,3.772472,0316284955,Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...